// created api in mongodb
String baseUrl = 'https://lavexbackend.onrender.com';
String registerUrl = '/api/user/register';
String loginUrl = '/api/user/login';
String proFormaUrl = '/api/porfarma/porpharmaCreate';
String invoiceUrl = '/api/invoice/invoiceCreate';
String debitUrl = '/api/debitnote/debitNoteCreate';
String creditUrl = '/api/creditnote/creditNoteCreate';
String addClientUrl = '/api/client/addClient';
String addSuppllierUrl = '/api/supplier/addSupplier';
String getProForma = '/api/invoices/myInvoices?type=';
String getallcompeney = "/api/company/allcompany";
String addcompeney = "/api/company/addCompany";
String deletecompeney = "/api/company/deleteCompany/";
String singlecompeney = "/api/company/getCompany/";
String updatecompeney = "/api/company/updateCompany/";
String getallclient = "/api/client/allClient";
String deleteclient = "/api/client/deleteClient/";
String getclient = "/api/client/clientdropdown";
String addinward = "/api/inward/addInward2";
String getInward = "/api/inward/allInward?paymentType=";
String addItem = '/api/itemMaster/addItemMaster';
String getallitem = '/api/itemMaster/allItemMaster';
String addbom = "/api/bom/addBom";
String singlebom = "/api/bom/getBom/";
String addproduction = "/api/production/addProduction2";
String deleteinward = "/api/inward/delInward/";
String getallbom = "/api/bom/allbom";
String getPurchaseStore = "/api/production/purchaseStore";
String updateItem = "/api/itemMaster/updatingItemMater/";
String productionentry = '/api/production/allProduction';
String updatestatus = '/api/production/changestatus/';
String productionstore = '/api/production/productionStore';
String allStock = '/api/production/allStock';
String preAndnow_production = '/api/production/prod/statuswithprev/';

// --------------------------------------------------------
String baseUrlTxt = 'https://zapwms.in/';
String myPaymentsEndUrlTxt = 'lavex_api/my_payments.php';
String supplierEndUrlTxt = 'lavex_api/supplier_payments.php';
String myClientEndUrlTxt = 'lavex_api/clients.php';
String itemMasterEndUrlTxt = '/lavex_api/items.php';
// String loginUrl = 'lavex_api//register.php';
String loginUrlTxt = 'lavex_api/login.php';
String comapanyUrlTxt = 'lavex_api/manage_firms.php';
String addItemUrlTxt = 'lavex_api/items_new.php';
